name: CI

on:
  push:
    branches: ["**"]
  pull_request:
permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Ruff
        run: ruff check . --output-format=github --ignore E501,B008 --line-length 120 --target-version py311

      - name: Bandit
        run: bandit -r . -x .venv -ll -b .bandit-baseline.json

      - name: Pytest
        run: pytest -q

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read version (version.txt)
        id: meta
        shell: bash
        run: |
          echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: docker buildx build -t ghcr.io/alexx6996/corporation-office/aioffice-staging-app:latest -t ghcr.io/alexx6996/corporation-office/aioffice-staging-app:${{ steps.meta.outputs.version }} -t ghcr.io/alexx6996/corporation-office/aioffice-staging-app:${{ github.sha }} --provenance=true --sbom=true --push .
